/**
 * Seed voice catalog into the database
 */
import { db, schema } from '../src/db/index.js'
import { eq } from 'drizzle-orm'

const voices = [
  { voice_id: "male-qn-qingse", voice_name: "Jovem tímido", language: "Chinês" },
  { voice_id: "male-qn-jingying", voice_name: "Jovem executivo", language: "Chinês" },
  { voice_id: "male-qn-badao", voice_name: "Jovem dominante", language: "Chinês" },
  { voice_id: "male-qn-daxuesheng", voice_name: "Universitário", language: "Chinês" },
  { voice_id: "female-shaonv", voice_name: "Garota jovem", language: "Chinês" },
  { voice_id: "female-yujie", voice_name: "Mulher confiante", language: "Chinês" },
  { voice_id: "female-chengshu", voice_name: "Mulher madura", language: "Chinês" },
  { voice_id: "female-tianmei", voice_name: "Mulher doce", language: "Chinês" },
  { voice_id: "male-qn-qingse-jingpin", voice_name: "Jovem tímido - beta", language: "Chinês" },
  { voice_id: "male-qn-jingying-jingpin", voice_name: "Jovem executivo - beta", language: "Chinês" },
  { voice_id: "male-qn-badao-jingpin", voice_name: "Jovem dominante - beta", language: "Chinês" },
  { voice_id: "male-qn-daxuesheng-jingpin", voice_name: "Universitário - beta", language: "Chinês" },
  { voice_id: "female-shaonv-jingpin", voice_name: "Garota jovem - beta", language: "Chinês" },
  { voice_id: "female-yujie-jingpin", voice_name: "Mulher confiante - beta", language: "Chinês" },
  { voice_id: "female-chengshu-jingpin", voice_name: "Mulher madura - beta", language: "Chinês" },
  { voice_id: "female-tianmei-jingpin", voice_name: "Mulher doce - beta", language: "Chinês" },
  { voice_id: "clever_boy", voice_name: "Menino esperto", language: "Chinês" },
  { voice_id: "cute_boy", voice_name: "Menino fofo", language: "Chinês" },
  { voice_id: "lovely_girl", voice_name: "Menina adorável", language: "Chinês" },
  { voice_id: "cartoon_pig", voice_name: "Porquinha de desenho", language: "Chinês" },
  { voice_id: "bingjiao_didi", voice_name: "Irmãozinho possessivo", language: "Chinês" },
  { voice_id: "junlang_nanyou", voice_name: "Namorado charmoso", language: "Chinês" },
  { voice_id: "chunzhen_xuedi", voice_name: "Calouro inocente", language: "Chinês" },
  { voice_id: "lengdan_xiongzhang", voice_name: "Veterano frio", language: "Chinês" },
  { voice_id: "badao_shaoye", voice_name: "Jovem mestre dominante", language: "Chinês" },
  { voice_id: "tianxin_xiaoling", voice_name: "Docinha Xiaoling", language: "Chinês" },
  { voice_id: "qiaopi_mengmei", voice_name: "Garota brincalhona", language: "Chinês" },
  { voice_id: "wumei_yujie", voice_name: "Mulher sedutora", language: "Chinês" },
  { voice_id: "diadia_xuemei", voice_name: "Caloura manhosa", language: "Chinês" },
  { voice_id: "danya_xuejie", voice_name: "Veterana elegante", language: "Chinês" },
  { voice_id: "Santa_Claus ", voice_name: "Santa Claus", language: "Inglês" },
  { voice_id: "Grinch", voice_name: "Grinch", language: "Inglês" },
  { voice_id: "Rudolph", voice_name: "Rudolph", language: "Inglês" },
  { voice_id: "Arnold", voice_name: "Arnold", language: "Inglês" },
  { voice_id: "Charming_Santa", voice_name: "Charming Santa", language: "Inglês" },
  { voice_id: "Charming_Lady", voice_name: "Charming Lady", language: "Inglês" },
  { voice_id: "Sweet_Girl", voice_name: "Sweet Girl", language: "Inglês" },
  { voice_id: "Cute_Elf", voice_name: "Cute Elf", language: "Inglês" },
  { voice_id: "Attractive_Girl", voice_name: "Attractive Girl", language: "Inglês" },
  { voice_id: "Serene_Woman", voice_name: "Serene Woman", language: "Inglês" },
  { voice_id: "Chinese (Mandarin)_Reliable_Executive", voice_name: "Executivo confiável", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_News_Anchor", voice_name: "Âncora de notícias", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Mature_Woman", voice_name: "Mulher madura e orgulhosa", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Unrestrained_Young_Man", voice_name: "Jovem rebelde", language: "Chinês" },
  { voice_id: "Arrogant_Miss", voice_name: "Senhorita arrogante", language: "Chinês" },
  { voice_id: "Robot_Armor", voice_name: "Armadura mecânica", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Kind-hearted_Antie", voice_name: "Tia prestativa", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_HK_Flight_Attendant", voice_name: "Comissária de bordo de Hong Kong", language: "Cantonês" },
  { voice_id: "Chinese (Mandarin)_Humorous_Elder", voice_name: "Senhor bem-humorado", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Gentleman", voice_name: "Homem gentil", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Warm_Bestie", voice_name: "Melhor amiga acolhedora", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Male_Announcer", voice_name: "Locutor masculino", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Sweet_Lady", voice_name: "Mulher doce", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Southern_Young_Man", voice_name: "Rapaz do sul", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Wise_Women", voice_name: "Mulher experiente", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Gentle_Youth", voice_name: "Jovem gentil", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Warm_Girl", voice_name: "Garota acolhedora", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Kind-hearted_Elder", voice_name: "Avó bondosa", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Cute_Spirit", voice_name: "Criatura fofa", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Radio_Host", voice_name: "Apresentador de rádio", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Lyrical_Voice", voice_name: "Voz lírica masculina", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Straightforward_Boy", voice_name: "Garoto sincero", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Sincere_Adult", voice_name: "Jovem adulto sincero", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Gentle_Senior", voice_name: "Veterana gentil", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Stubborn_Friend", voice_name: "Amigo teimoso", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Crisp_Girl", voice_name: "Garota de voz clara", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Pure-hearted_Boy", voice_name: "Garoto puro e vizinho", language: "Chinês" },
  { voice_id: "Chinese (Mandarin)_Soft_Girl", voice_name: "Garota delicada", language: "Chinês" },
  { voice_id: "Cantonese_ProfessionalHost（F)", voice_name: "Apresentadora profissional", language: "Cantonês" },
  { voice_id: "Cantonese_GentleLady", voice_name: "Mulher gentil", language: "Cantonês" },
  { voice_id: "Cantonese_ProfessionalHost（M)", voice_name: "Apresentador profissional", language: "Cantonês" },
  { voice_id: "Cantonese_PlayfulMan", voice_name: "Homem brincalhão", language: "Cantonês" },
  { voice_id: "Cantonese_CuteGirl", voice_name: "Garota fofa", language: "Cantonês" },
  { voice_id: "Cantonese_KindWoman", voice_name: "Mulher bondosa", language: "Cantonês" },
  { voice_id: "English_Trustworthy_Man", voice_name: "Trustworthy Man", language: "Inglês" },
  { voice_id: "English_Graceful_Lady", voice_name: "Graceful Lady", language: "Inglês" },
  { voice_id: "English_Aussie_Bloke", voice_name: "Aussie Bloke", language: "Inglês" },
  { voice_id: "English_Whispering_girl", voice_name: "Whispering girl", language: "Inglês" },
  { voice_id: "English_Diligent_Man", voice_name: "Diligent Man", language: "Inglês" },
  { voice_id: "English_Gentle-voiced_man", voice_name: "Gentle-voiced man", language: "Inglês" },
  { voice_id: "Japanese_IntellectualSenior", voice_name: "Intellectual Senior", language: "Japonês" },
  { voice_id: "Japanese_DecisivePrincess", voice_name: "Decisive Princess", language: "Japonês" },
  { voice_id: "Japanese_LoyalKnight", voice_name: "Loyal Knight", language: "Japonês" },
  { voice_id: "Japanese_DominantMan", voice_name: "Dominant Man", language: "Japonês" },
  { voice_id: "Japanese_SeriousCommander", voice_name: "Serious Commander", language: "Japonês" },
  { voice_id: "Japanese_ColdQueen", voice_name: "Cold Queen", language: "Japonês" },
  { voice_id: "Japanese_DependableWoman", voice_name: "Dependable Woman", language: "Japonês" },
  { voice_id: "Japanese_GentleButler", voice_name: "Gentle Butler", language: "Japonês" },
  { voice_id: "Japanese_KindLady", voice_name: "Kind Lady", language: "Japonês" },
  { voice_id: "Japanese_CalmLady", voice_name: "Calm Lady", language: "Japonês" },
  { voice_id: "Japanese_OptimisticYouth", voice_name: "Optimistic Youth", language: "Japonês" },
  { voice_id: "Japanese_GenerousIzakayaOwner", voice_name: "Generous Izakaya Owner", language: "Japonês" },
  { voice_id: "Japanese_SportyStudent", voice_name: "Sporty Student", language: "Japonês" },
  { voice_id: "Japanese_InnocentBoy", voice_name: "Innocent Boy", language: "Japonês" },
  { voice_id: "Japanese_GracefulMaiden", voice_name: "Graceful Maiden", language: "Japonês" },
  { voice_id: "Dutch_kindhearted_girl", voice_name: "Kind-hearted girl", language: "Holandês" },
  { voice_id: "Dutch_bossy_leader", voice_name: "Bossy leader", language: "Holandês" },
  { voice_id: "Vietnamese_kindhearted_girl", voice_name: "Kind-hearted girl", language: "Vietnamita" },
  { voice_id: "Korean_SweetGirl", voice_name: "Sweet Girl", language: "Coreano" },
  { voice_id: "Korean_CheerfulBoyfriend", voice_name: "Cheerful Boyfriend", language: "Coreano" },
  { voice_id: "Korean_EnchantingSister", voice_name: "Enchanting Sister", language: "Coreano" },
  { voice_id: "Korean_ShyGirl", voice_name: "Shy Girl", language: "Coreano" },
  { voice_id: "Korean_ReliableSister", voice_name: "Reliable Sister", language: "Coreano" },
  { voice_id: "Korean_StrictBoss", voice_name: "Strict Boss", language: "Coreano" },
  { voice_id: "Korean_SassyGirl", voice_name: "Sassy Girl", language: "Coreano" },
  { voice_id: "Korean_ChildhoodFriendGirl", voice_name: "Childhood Friend Girl", language: "Coreano" },
  { voice_id: "Korean_PlayboyCharmer", voice_name: "Playboy Charmer", language: "Coreano" },
  { voice_id: "Korean_ElegantPrincess", voice_name: "Elegant Princess", language: "Coreano" },
  { voice_id: "Korean_BraveFemaleWarrior", voice_name: "Brave Female Warrior", language: "Coreano" },
  { voice_id: "Korean_BraveYouth", voice_name: "Brave Youth", language: "Coreano" },
  { voice_id: "Korean_CalmLady", voice_name: "Calm Lady", language: "Coreano" },
  { voice_id: "Korean_EnthusiasticTeen", voice_name: "Enthusiastic Teen", language: "Coreano" },
  { voice_id: "Korean_SoothingLady", voice_name: "Soothing Lady", language: "Coreano" },
  { voice_id: "Korean_IntellectualSenior", voice_name: "Intellectual Senior", language: "Coreano" },
  { voice_id: "Korean_LonelyWarrior", voice_name: "Lonely Warrior", language: "Coreano" },
  { voice_id: "Korean_MatureLady", voice_name: "Mature Lady", language: "Coreano" },
  { voice_id: "Korean_InnocentBoy", voice_name: "Innocent Boy", language: "Coreano" },
  { voice_id: "Korean_CharmingSister", voice_name: "Charming Sister", language: "Coreano" },
  { voice_id: "Korean_AthleticStudent", voice_name: "Athletic Student", language: "Coreano" },
  { voice_id: "Korean_BraveAdventurer", voice_name: "Brave Adventurer", language: "Coreano" },
  { voice_id: "Korean_CalmGentleman", voice_name: "Calm Gentleman", language: "Coreano" },
  { voice_id: "Korean_WiseElf", voice_name: "Wise Elf", language: "Coreano" },
  { voice_id: "Korean_CheerfulCoolJunior", voice_name: "Cheerful Cool Junior", language: "Coreano" },
  { voice_id: "Korean_DecisiveQueen", voice_name: "Decisive Queen", language: "Coreano" },
  { voice_id: "Korean_ColdYoungMan", voice_name: "Cold Young Man", language: "Coreano" },
  { voice_id: "Korean_MysteriousGirl", voice_name: "Mysterious Girl", language: "Coreano" },
  { voice_id: "Korean_QuirkyGirl", voice_name: "Quirky Girl", language: "Coreano" },
  { voice_id: "Korean_ConsiderateSenior", voice_name: "Considerate Senior", language: "Coreano" },
  { voice_id: "Korean_CheerfulLittleSister", voice_name: "Cheerful Little Sister", language: "Coreano" },
  { voice_id: "Korean_DominantMan", voice_name: "Dominant Man", language: "Coreano" },
  { voice_id: "Korean_AirheadedGirl", voice_name: "Airheaded Girl", language: "Coreano" },
  { voice_id: "Korean_ReliableYouth", voice_name: "Reliable Youth", language: "Coreano" },
  { voice_id: "Korean_FriendlyBigSister", voice_name: "Friendly Big Sister", language: "Coreano" },
  { voice_id: "Korean_GentleBoss", voice_name: "Gentle Boss", language: "Coreano" },
  { voice_id: "Korean_ColdGirl", voice_name: "Cold Girl", language: "Coreano" },
  { voice_id: "Korean_HaughtyLady", voice_name: "Haughty Lady", language: "Coreano" },
  { voice_id: "Korean_CharmingElderSister", voice_name: "Charming Elder Sister", language: "Coreano" },
  { voice_id: "Korean_IntellectualMan", voice_name: "Intellectual Man", language: "Coreano" },
  { voice_id: "Korean_CaringWoman", voice_name: "Caring Woman", language: "Coreano" },
  { voice_id: "Korean_WiseTeacher", voice_name: "Wise Teacher", language: "Coreano" },
  { voice_id: "Korean_ConfidentBoss", voice_name: "Confident Boss", language: "Coreano" },
  { voice_id: "Korean_AthleticGirl", voice_name: "Athletic Girl", language: "Coreano" },
  { voice_id: "Korean_PossessiveMan", voice_name: "Possessive Man", language: "Coreano" },
  { voice_id: "Korean_GentleWoman", voice_name: "Gentle Woman", language: "Coreano" },
  { voice_id: "Korean_CockyGuy", voice_name: "Cocky Guy", language: "Coreano" },
  { voice_id: "Korean_ThoughtfulWoman", voice_name: "Thoughtful Woman", language: "Coreano" },
  { voice_id: "Korean_OptimisticYouth", voice_name: "Optimistic Youth", language: "Coreano" },
  { voice_id: "Spanish_SereneWoman", voice_name: "Serene Woman", language: "Espanhol" },
  { voice_id: "Spanish_MaturePartner", voice_name: "Mature Partner", language: "Espanhol" },
  { voice_id: "Spanish_CaptivatingStoryteller", voice_name: "Captivating Storyteller", language: "Espanhol" },
  { voice_id: "Spanish_Narrator", voice_name: "Narrator", language: "Espanhol" },
  { voice_id: "Spanish_WiseScholar", voice_name: "Wise Scholar", language: "Espanhol" },
  { voice_id: "Spanish_Kind-heartedGirl", voice_name: "Kind-hearted Girl", language: "Espanhol" },
  { voice_id: "Spanish_DeterminedManager", voice_name: "Determined Manager", language: "Espanhol" },
  { voice_id: "Spanish_BossyLeader", voice_name: "Bossy Leader", language: "Espanhol" },
  { voice_id: "Spanish_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Espanhol" },
  { voice_id: "Spanish_ConfidentWoman", voice_name: "Confident Woman", language: "Espanhol" },
  { voice_id: "Spanish_ThoughtfulMan", voice_name: "Thoughtful Man", language: "Espanhol" },
  { voice_id: "Spanish_Strong-WilledBoy", voice_name: "Strong-willed Boy", language: "Espanhol" },
  { voice_id: "Spanish_SophisticatedLady", voice_name: "Sophisticated Lady", language: "Espanhol" },
  { voice_id: "Spanish_RationalMan", voice_name: "Rational Man", language: "Espanhol" },
  { voice_id: "Spanish_AnimeCharacter", voice_name: "Anime Character", language: "Espanhol" },
  { voice_id: "Spanish_Deep-tonedMan", voice_name: "Deep-toned Man", language: "Espanhol" },
  { voice_id: "Spanish_Fussyhostess", voice_name: "Fussy hostess", language: "Espanhol" },
  { voice_id: "Spanish_SincereTeen", voice_name: "Sincere Teen", language: "Espanhol" },
  { voice_id: "Spanish_FrankLady", voice_name: "Frank Lady", language: "Espanhol" },
  { voice_id: "Spanish_Comedian", voice_name: "Comedian", language: "Espanhol" },
  { voice_id: "Spanish_Debator", voice_name: "Debator", language: "Espanhol" },
  { voice_id: "Spanish_ToughBoss", voice_name: "Tough Boss", language: "Espanhol" },
  { voice_id: "Spanish_Wiselady", voice_name: "Wise Lady", language: "Espanhol" },
  { voice_id: "Spanish_Steadymentor", voice_name: "Steady Mentor", language: "Espanhol" },
  { voice_id: "Spanish_Jovialman", voice_name: "Jovial Man", language: "Espanhol" },
  { voice_id: "Spanish_SantaClaus", voice_name: "Santa Claus", language: "Espanhol" },
  { voice_id: "Spanish_Rudolph", voice_name: "Rudolph", language: "Espanhol" },
  { voice_id: "Spanish_Intonategirl", voice_name: "Intonate Girl", language: "Espanhol" },
  { voice_id: "Spanish_Arnold", voice_name: "Arnold", language: "Espanhol" },
  { voice_id: "Spanish_Ghost", voice_name: "Ghost", language: "Espanhol" },
  { voice_id: "Spanish_HumorousElder", voice_name: "Humorous Elder", language: "Espanhol" },
  { voice_id: "Spanish_EnergeticBoy", voice_name: "Energetic Boy", language: "Espanhol" },
  { voice_id: "Spanish_WhimsicalGirl", voice_name: "Whimsical Girl", language: "Espanhol" },
  { voice_id: "Spanish_StrictBoss", voice_name: "Strict Boss", language: "Espanhol" },
  { voice_id: "Spanish_ReliableMan", voice_name: "Reliable Man", language: "Espanhol" },
  { voice_id: "Spanish_SereneElder", voice_name: "Serene Elder", language: "Espanhol" },
  { voice_id: "Spanish_AngryMan", voice_name: "Angry Man", language: "Espanhol" },
  { voice_id: "Spanish_AssertiveQueen", voice_name: "Assertive Queen", language: "Espanhol" },
  { voice_id: "Spanish_CaringGirlfriend", voice_name: "Caring Girlfriend", language: "Espanhol" },
  { voice_id: "Spanish_PowerfulSoldier", voice_name: "Powerful Soldier", language: "Espanhol" },
  { voice_id: "Spanish_PassionateWarrior", voice_name: "Passionate Warrior", language: "Espanhol" },
  { voice_id: "Spanish_ChattyGirl", voice_name: "Chatty Girl", language: "Espanhol" },
  { voice_id: "Spanish_RomanticHusband", voice_name: "Romantic Husband", language: "Espanhol" },
  { voice_id: "Spanish_CompellingGirl", voice_name: "Compelling Girl", language: "Espanhol" },
  { voice_id: "Spanish_PowerfulVeteran", voice_name: "Powerful Veteran", language: "Espanhol" },
  { voice_id: "Spanish_SensibleManager", voice_name: "Sensible Manager", language: "Espanhol" },
  { voice_id: "Spanish_ThoughtfulLady", voice_name: "Thoughtful Lady", language: "Espanhol" },
  { voice_id: "Portuguese_SentimentalLady", voice_name: "Sentimental Lady", language: "Português" },
  { voice_id: "Portuguese_BossyLeader", voice_name: "Bossy Leader", language: "Português" },
  { voice_id: "Portuguese_Wiselady", voice_name: "Wise lady", language: "Português" },
  { voice_id: "Portuguese_Strong-WilledBoy", voice_name: "Strong-willed Boy", language: "Português" },
  { voice_id: "Portuguese_Deep-VoicedGentleman", voice_name: "Deep-voiced Gentleman", language: "Português" },
  { voice_id: "Portuguese_UpsetGirl", voice_name: "Upset Girl", language: "Português" },
  { voice_id: "Portuguese_PassionateWarrior", voice_name: "Passionate Warrior", language: "Português" },
  { voice_id: "Portuguese_AnimeCharacter", voice_name: "Anime Character", language: "Português" },
  { voice_id: "Portuguese_ConfidentWoman", voice_name: "Confident Woman", language: "Português" },
  { voice_id: "Portuguese_AngryMan", voice_name: "Angry Man", language: "Português" },
  { voice_id: "Portuguese_CaptivatingStoryteller", voice_name: "Captivating Storyteller", language: "Português" },
  { voice_id: "Portuguese_Godfather", voice_name: "Godfather", language: "Português" },
  { voice_id: "Portuguese_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Português" },
  { voice_id: "Portuguese_SmartYoungGirl", voice_name: "Smart Young Girl", language: "Português" },
  { voice_id: "Portuguese_Kind-heartedGirl", voice_name: "Kind-hearted Girl", language: "Português" },
  { voice_id: "Portuguese_Pompouslady", voice_name: "Pompous lady", language: "Português" },
  { voice_id: "Portuguese_Grinch", voice_name: "Grinch", language: "Português" },
  { voice_id: "Portuguese_Debator", voice_name: "Debator", language: "Português" },
  { voice_id: "Portuguese_SweetGirl", voice_name: "Sweet Girl", language: "Português" },
  { voice_id: "Portuguese_AttractiveGirl", voice_name: "Attractive Girl", language: "Português" },
  { voice_id: "Portuguese_ThoughtfulMan", voice_name: "Thoughtful Man", language: "Português" },
  { voice_id: "Portuguese_PlayfulGirl", voice_name: "Playful Girl", language: "Português" },
  { voice_id: "Portuguese_GorgeousLady", voice_name: "Gorgeous Lady", language: "Português" },
  { voice_id: "Portuguese_LovelyLady", voice_name: "Lovely Lady", language: "Português" },
  { voice_id: "Portuguese_SereneWoman", voice_name: "Serene Woman", language: "Português" },
  { voice_id: "Portuguese_SadTeen", voice_name: "Sad Teen", language: "Português" },
  { voice_id: "Portuguese_MaturePartner", voice_name: "Mature Partner", language: "Português" },
  { voice_id: "Portuguese_Comedian", voice_name: "Comedian", language: "Português" },
  { voice_id: "Portuguese_NaughtySchoolgirl", voice_name: "Naughty Schoolgirl", language: "Português" },
  { voice_id: "Portuguese_Narrator", voice_name: "Narrator", language: "Português" },
  { voice_id: "Portuguese_ToughBoss", voice_name: "Tough Boss", language: "Português" },
  { voice_id: "Portuguese_Fussyhostess", voice_name: "Fussy hostess", language: "Português" },
  { voice_id: "Portuguese_Dramatist", voice_name: "Dramatist", language: "Português" },
  { voice_id: "Portuguese_Steadymentor", voice_name: "Steady Mentor", language: "Português" },
  { voice_id: "Portuguese_Jovialman", voice_name: "Jovial Man", language: "Português" },
  { voice_id: "Portuguese_CharmingQueen", voice_name: "Charming Queen", language: "Português" },
  { voice_id: "Portuguese_SantaClaus", voice_name: "Santa Claus", language: "Português" },
  { voice_id: "Portuguese_Rudolph", voice_name: "Rudolph", language: "Português" },
  { voice_id: "Portuguese_Arnold", voice_name: "Arnold", language: "Português" },
  { voice_id: "Portuguese_CharmingSanta", voice_name: "Charming Santa", language: "Português" },
  { voice_id: "Portuguese_CharmingLady", voice_name: "Charming Lady", language: "Português" },
  { voice_id: "Portuguese_Ghost", voice_name: "Ghost", language: "Português" },
  { voice_id: "Portuguese_HumorousElder", voice_name: "Humorous Elder", language: "Português" },
  { voice_id: "Portuguese_CalmLeader", voice_name: "Calm Leader", language: "Português" },
  { voice_id: "Portuguese_GentleTeacher", voice_name: "Gentle Teacher", language: "Português" },
  { voice_id: "Portuguese_EnergeticBoy", voice_name: "Energetic Boy", language: "Português" },
  { voice_id: "Portuguese_ReliableMan", voice_name: "Reliable Man", language: "Português" },
  { voice_id: "Portuguese_SereneElder", voice_name: "Serene Elder", language: "Português" },
  { voice_id: "Portuguese_GrimReaper", voice_name: "Grim Reaper", language: "Português" },
  { voice_id: "Portuguese_AssertiveQueen", voice_name: "Assertive Queen", language: "Português" },
  { voice_id: "Portuguese_WhimsicalGirl", voice_name: "Whimsical Girl", language: "Português" },
  { voice_id: "Portuguese_StressedLady", voice_name: "Stressed Lady", language: "Português" },
  { voice_id: "Portuguese_FriendlyNeighbor", voice_name: "Friendly Neighbor", language: "Português" },
  { voice_id: "Portuguese_CaringGirlfriend", voice_name: "Caring Girlfriend", language: "Português" },
  { voice_id: "Portuguese_PowerfulSoldier", voice_name: "Powerful Soldier", language: "Português" },
  { voice_id: "Portuguese_FascinatingBoy", voice_name: "Fascinating Boy", language: "Português" },
  { voice_id: "Portuguese_RomanticHusband", voice_name: "Romantic Husband", language: "Português" },
  { voice_id: "Portuguese_StrictBoss", voice_name: "Strict Boss", language: "Português" },
  { voice_id: "Portuguese_InspiringLady", voice_name: "Inspiring Lady", language: "Português" },
  { voice_id: "Portuguese_PlayfulSpirit", voice_name: "Playful Spirit", language: "Português" },
  { voice_id: "Portuguese_ElegantGirl", voice_name: "Elegant Girl", language: "Português" },
  { voice_id: "Portuguese_CompellingGirl", voice_name: "Compelling Girl", language: "Português" },
  { voice_id: "Portuguese_PowerfulVeteran", voice_name: "Powerful Veteran", language: "Português" },
  { voice_id: "Portuguese_SensibleManager", voice_name: "Sensible Manager", language: "Português" },
  { voice_id: "Portuguese_ThoughtfulLady", voice_name: "Thoughtful Lady", language: "Português" },
  { voice_id: "Portuguese_TheatricalActor", voice_name: "Theatrical Actor", language: "Português" },
  { voice_id: "Portuguese_FragileBoy", voice_name: "Fragile Boy", language: "Português" },
  { voice_id: "Portuguese_ChattyGirl", voice_name: "Chatty Girl", language: "Português" },
  { voice_id: "Portuguese_Conscientiousinstructor", voice_name: "Conscientious Instructor", language: "Português" },
  { voice_id: "Portuguese_RationalMan", voice_name: "Rational Man", language: "Português" },
  { voice_id: "Portuguese_WiseScholar", voice_name: "Wise Scholar", language: "Português" },
  { voice_id: "Portuguese_FrankLady", voice_name: "Frank Lady", language: "Português" },
  { voice_id: "Portuguese_DeterminedManager", voice_name: "Determined Manager", language: "Português" },
  { voice_id: "French_Male_Speech_New", voice_name: "Level-Headed Man", language: "Francês" },
  { voice_id: "French_Female_News Anchor", voice_name: "Patient Female Presenter", language: "Francês" },
  { voice_id: "French_CasualMan", voice_name: "Casual Man", language: "Francês" },
  { voice_id: "French_MovieLeadFemale", voice_name: "Movie Lead Female", language: "Francês" },
  { voice_id: "French_FemaleAnchor", voice_name: "Female Anchor", language: "Francês" },
  { voice_id: "French_MaleNarrator", voice_name: "Male Narrator", language: "Francês" },
  { voice_id: "Indonesian_SweetGirl", voice_name: "Sweet Girl", language: "Indonésio" },
  { voice_id: "Indonesian_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Indonésio" },
  { voice_id: "Indonesian_CharmingGirl", voice_name: "Charming Girl", language: "Indonésio" },
  { voice_id: "Indonesian_CalmWoman", voice_name: "Calm Woman", language: "Indonésio" },
  { voice_id: "Indonesian_ConfidentWoman", voice_name: "Confident Woman", language: "Indonésio" },
  { voice_id: "Indonesian_CaringMan", voice_name: "Caring Man", language: "Indonésio" },
  { voice_id: "Indonesian_BossyLeader", voice_name: "Bossy Leader", language: "Indonésio" },
  { voice_id: "Indonesian_DeterminedBoy", voice_name: "Determined Boy", language: "Indonésio" },
  { voice_id: "Indonesian_GentleGirl", voice_name: "Gentle Girl", language: "Indonésio" },
  { voice_id: "German_FriendlyMan", voice_name: "Friendly Man", language: "Alemão" },
  { voice_id: "German_SweetLady", voice_name: "Sweet Lady", language: "Alemão" },
  { voice_id: "German_PlayfulMan", voice_name: "Playful Man", language: "Alemão" },
  { voice_id: "Russian_HandsomeChildhoodFriend", voice_name: "Handsome Childhood Friend", language: "Russo" },
  { voice_id: "Russian_BrightHeroine", voice_name: "Bright Queen", language: "Russo" },
  { voice_id: "Russian_AmbitiousWoman", voice_name: "Ambitious Woman", language: "Russo" },
  { voice_id: "Russian_ReliableMan", voice_name: "Reliable Man", language: "Russo" },
  { voice_id: "Russian_CrazyQueen", voice_name: "Crazy Girl", language: "Russo" },
  { voice_id: "Russian_PessimisticGirl", voice_name: "Pessimistic Girl", language: "Russo" },
  { voice_id: "Russian_AttractiveGuy", voice_name: "Attractive Guy", language: "Russo" },
  { voice_id: "Russian_Bad-temperedBoy", voice_name: "Bad-tempered Boy", language: "Russo" },
  { voice_id: "Italian_BraveHeroine", voice_name: "Brave Heroine", language: "Italiano" },
  { voice_id: "Italian_Narrator", voice_name: "Narrator", language: "Italiano" },
  { voice_id: "Italian_WanderingSorcerer", voice_name: "Wandering Sorcerer", language: "Italiano" },
  { voice_id: "Italian_DiligentLeader", voice_name: "Diligent Leader", language: "Italiano" },
  { voice_id: "Arabic_CalmWoman", voice_name: "Calm Woman", language: "Árabe" },
  { voice_id: "Arabic_FriendlyGuy", voice_name: "Friendly Guy", language: "Árabe" },
  { voice_id: "Turkish_CalmWoman", voice_name: "Calm Woman", language: "Turco" },
  { voice_id: "Turkish_Trustworthyman", voice_name: "Trustworthy man", language: "Turco" },
  { voice_id: "Ukrainian_CalmWoman", voice_name: "Calm Woman", language: "Ucraniano" },
  { voice_id: "Ukrainian_WiseScholar", voice_name: "Wise Scholar", language: "Ucraniano" },
]

const ts = new Date().toISOString()

// Clear previous data
db.delete(schema.aiVoices).run()

// Bulk insert
const insertRows = voices.map(v => ({
  voiceId: v.voice_id,
  voiceName: v.voice_name,
  description: '[]',
  language: v.language,
  provider: 'minimax',
  createdAt: ts,
}))

db.insert(schema.aiVoices).values(insertRows).run()

console.log(`✅ ${voices.length} vozes inseridas`)
