import { describe, expect, it } from 'vitest'
import {
  buildCharacterMentions,
  buildCharacterCandidates,
  buildStructuralExtraction,
  classifyEntityKind,
  extractSceneCandidates,
  isGhostCharacterName,
  isGhostPropName,
  isSameSceneCandidate,
  isSamePropIdentity,
  reconcileCharactersAgainstExisting,
  resolveCanonicalPropName,
  sanitizeCharacterCandidates,
  sanitizePropCandidates,
  sanitizeSceneCandidates,
} from './extraction-entities.js'

describe('extraction entity classification', () => {
  it('classifies named ships as props instead of characters', () => {
    expect(classifyEntityKind({
      name: 'Hms',
      description: 'O mar violento arremessa o HMS Wager contra a rocha escura.',
    })).toBe('prop')
  })

  it('promotes ship acronyms to the full canonical ship name when context exists', () => {
    expect(resolveCanonicalPropName('Hms', 'O HMS Wager quase afunda durante a tempestade.')).toBe('HMS Wager')
  })

  it('trims trailing stopwords from ship names inferred from prose', () => {
    expect(resolveCanonicalPropName('HMS Wager O', 'O HMS Wager contra a rocha escura.')).toBe('HMS Wager')
  })

  it('trims malformed trailing ship fragments from prose extraction noise', () => {
    expect(resolveCanonicalPropName('HMS Wager Não HMS', 'HMS Wager não resiste ao impacto.')).toBe('HMS Wager')
  })

  it('keeps human roles as characters while diverting object-like entities to props', () => {
    const result = sanitizeCharacterCandidates([
      {
        name: 'Capitão David Cheap',
        description: 'Capitão David Cheap grita ordens para salvar a tripulação.',
      },
      {
        name: 'Hms',
        description: 'O HMS Wager perde o leme e bate contra as pedras.',
      },
    ])

    expect(result.characters.map(item => item.name)).toEqual(['Capitão David Cheap'])
    expect(result.props.map(item => item.name)).toEqual(['HMS Wager'])
  })

  it('rejects ghost character labels generated by loose screenplay rewrites', () => {
    expect(isGhostCharacterName('Oficial 1')).toBe(true)
    expect(isGhostCharacterName('Marinheiro Enfraquecido')).toBe(true)
    expect(isGhostCharacterName('Voz do Oficial')).toBe(true)
    expect(isGhostCharacterName('Fim Do Roteiro')).toBe(true)
    expect(isGhostCharacterName('E')).toBe(true)
    expect(isGhostCharacterName('Marinheiro Tom')).toBe(false)
    expect(isGhostCharacterName('Oficial James')).toBe(false)
  })

  it('merges titled aliases into the more specific named character', () => {
    const result = sanitizeCharacterCandidates([
      {
        name: 'Capitão David Cheap',
        description: 'Capitão David Cheap está ferido e tenta manter o comando.',
      },
      {
        name: 'Capitão Cheap',
        description: 'Capitão Cheap insiste que ainda é o comandante.',
      },
    ])

    expect(result.characters).toHaveLength(1)
    expect(result.characters[0]?.name).toBe('Capitão David Cheap')
  })

  it('extracts titled names from prose and keeps the canonical titled character', () => {
    const script = [
      '## S1 | Exterior · Praia Desolada da Patagônia | Dia',
      '',
      'O capitão DAVID CHEAP, ferido, tenta manter o comando enquanto os homens hesitam.',
    ].join('\n')

    const scenes = extractSceneCandidates(script)
    const characters = buildCharacterCandidates(script, scenes)

    expect(characters.map(item => item.name)).toContain('Capitão David Cheap')
    expect(characters.map(item => item.name)).not.toContain('David Cheap')
  })

  it('rejects malformed prop fragments that came from prose instead of real object names', () => {
    expect(isGhostPropName('navio afundar')).toBe(true)
    expect(isGhostPropName('navio está despedaçado')).toBe(true)
    expect(isGhostPropName('arma improvisada O medo')).toBe(true)
    expect(isGhostPropName('HMS Wager')).toBe(false)
    expect(isGhostPropName('barco da colônia espanhola')).toBe(false)
  })

  it('rejects prose fragments that masquerade as named props', () => {
    const result = sanitizePropCandidates([
      { name: 'navio disciplinado Herda um', description: 'navio disciplinado Herda um destino cruel.' },
      { name: 'HMS Victory', description: 'O HMS Victory avança em mar aberto.' },
    ])

    expect(result).toHaveLength(1)
    expect(result[0]?.name).toBe('HMS Victory')
  })

  it('treats malformed ship aliases as the same canonical prop identity', () => {
    expect(isSamePropIdentity('HMS Wager', 'HMS Wager Não HMS')).toBe(true)
  })

  it('deduplicates canonical props that refer to the same ship', () => {
    const result = sanitizePropCandidates([
      { name: 'HMS Wager', description: 'Navio britânico lançado contra as rochas.' },
      { name: 'HMS Wager Não HMS', description: 'HMS Wager não resiste à tempestade.' },
    ])

    expect(result).toHaveLength(1)
    expect(result[0]?.name).toBe('HMS Wager')
  })

  it('treats generic and specific time variants as the same scene when location identity matches strongly', () => {
    expect(isSameSceneCandidate(
      { location: 'Costa da Patagônia Chilena', time: 'Maio de 1741' },
      { location: 'Costa da Patagônia', time: '1741' },
    )).toBe(true)
  })

  it('reuses scene candidates with the same core location even when one variant says praia and another says costa', () => {
    expect(isSameSceneCandidate(
      { location: 'Acampamento improvisado na praia', time: 'Dias depois, 1741' },
      { location: 'Acampamento improvisado na costa', time: '1741' },
    )).toBe(true)
  })

  it('treats the same canonical location as one reusable set even when time variants conflict', () => {
    expect(isSameSceneCandidate(
      { location: 'A bordo do HMS Victory', time: 'Travessia do Atlântico, 1740–1741' },
      { location: 'A bordo do HMS Victory', time: 'Próximo ao Cabo Horn, 1741' },
    )).toBe(true)
  })

  it('does not collapse different ship scene families just because they share the same vessel name', () => {
    expect(isSameSceneCandidate(
      { location: 'A bordo do HMS Victory', time: '1741' },
      { location: 'HMS Victory em mar aberto', time: '1741' },
    )).toBe(false)
  })

  it('does not merge distinct island scenes that only share one weak token', () => {
    expect(isSameSceneCandidate(
      { location: 'Praia e barrancos da ilha', time: 'Dias depois, 1741' },
      { location: 'Praia e margem da floresta', time: '1741' },
    )).toBe(false)
  })

  it('normalizes reusable shipboard sets without hardcoding a specific vessel', () => {
    const scenes = sanitizeSceneCandidates([
      {
        location: 'Convés do HMS Victory, enquanto a chuva cai',
        time: 'Noite',
        prompt: 'Convés do HMS Victory, enquanto a chuva cai',
      },
      {
        location: 'Cabine de comando do HMS Victory',
        time: 'Noite',
        prompt: 'Cabine de comando do HMS Victory',
      },
    ])

    expect(scenes).toHaveLength(1)
    expect(scenes[0]?.location).toBe('A bordo do HMS Victory')
  })

  it('collapses duplicate canonical shipboard sets into one scene even when time is different', () => {
    const scenes = sanitizeSceneCandidates([
      {
        location: 'A bordo do HMS Victory',
        time: 'Travessia do Atlântico, 1740–1741',
        prompt: 'A bordo do HMS Victory · Travessia do Atlântico, 1740–1741',
      },
      {
        location: 'A bordo do HMS Victory',
        time: 'Próximo ao Cabo Horn, 1741',
        prompt: 'A bordo do HMS Victory · Próximo ao Cabo Horn, 1741',
      },
    ])

    expect(scenes).toHaveLength(1)
    expect(scenes[0]?.location).toBe('A bordo do HMS Victory')
    expect(scenes[0]?.time || '').toBe('')
  })

  it('builds explicit character mentions with evidence instead of guessing directly from candidate names', () => {
    const script = [
      '## S1 | Exterior · Praia Desolada | Dia',
      '',
      'Capitão David Cheap: Mantenham o rumo.',
      'O oficial James hesita antes de responder.',
    ].join('\n')

    const mentions = buildCharacterMentions(script)

    expect(mentions.map((item) => item.canonicalName)).toContain('Capitão David Cheap')
    expect(mentions.some((item) => item.signal === 'dialogue')).toBe(true)
    expect(mentions.every((item) => item.sourceSpan.startsWith('scene:'))).toBe(true)
  })

  it('reconciles structural extraction to canonical screenplay entities before persistence', () => {
    const script = [
      '## S1 | Exterior · Praia Desolada da Patagônia | Dia',
      '',
      'O capitão DAVID CHEAP, ferido, tenta manter o comando enquanto os homens hesitam.',
      'O HMS WAGER resiste ao impacto nas rochas.',
    ].join('\n')

    const extracted = buildStructuralExtraction(script)

    expect(extracted.characters.map((item) => item.name)).toEqual(['Capitão David Cheap'])
    expect(extracted.props.map((item) => item.name)).toEqual(['HMS Wager'])
    expect(extracted.mentions.characters.length).toBeGreaterThan(0)
    expect(extracted.mentions.props.length).toBeGreaterThan(0)
  })

  it('reconciles extracted characters against existing drama entities before save', () => {
    const reconciled = reconcileCharactersAgainstExisting(
      [
        {
          name: 'Capitão Cheap',
          description: 'Capitão Cheap insiste que ainda consegue comandar.',
          sourceQuote: 'Capitão Cheap insiste que ainda consegue comandar.',
        },
      ],
      [
        {
          id: 1,
          name: 'Capitão David Cheap',
          role: 'Protagonista',
          description: 'Comandante ferido da expedição.',
          appearance: '',
          personality: '',
          deletedAt: null,
        },
      ],
    )

    expect(reconciled).toHaveLength(1)
    expect(reconciled[0]?.name).toBe('Capitão David Cheap')
  })
})
